### PR TITLE
more pylint fixes

### PR DESCRIPTION
**Pull request by jlebon**

### CODE REVIEW

**Comment by rhatdan** [comment]
Why are you removing bad-builtin?  Do we want to remove this check from the Makefile?

**Comment by jlebon** [comment]
It was moved to an extension in pylint 1.6:

> The bad-builtin check was moved into an extension.
> 
> The check was complaining about used builtin functions which were supposed to not be used. For instance, map and filter were falling into this category, since better alternatives can be used, such as list comprehensions. But the check was annoying, since using map or filter can have its use cases and as such, we decided to move it to an extension check instead. It can now be enabled through --load-plugins=pylint.extensions.bad_builtin.

https://docs.pylint.org/en/latest/whatsnew/1.6.html#other-changes

So if we want to re-enable them, we have to add the `--load-plugins` tidbit to the Makefile. Though I don't think it's that great of a warning (they want you to use list comprehensions instead, see http://pylint-messages.wikidot.com/messages:w0141), which I suppose is why they moved it off from the core.

**Comment by rhatdan** [comment]
Ok I think we should remove this and remove the check then.  I think I am only seeing this checked in python2 version.

**Comment by rhatdan** [comment]
Removed.

**Pull request closed without merging**
